### ISSUE TITLE
ATLAN-JAVA-403-000 Server responded with ATLAS-403-00-001: service-account-apikey-9bff22c3-a69a-46dc-8c46-e8bf3c88cfbe is not authorized to perform read entity: guid

### ISSUE THREAD

**Issue by archenroot** [atlanhq/atlan-java#393]
I am in situation which I don't understand, maybe its related to ATLAS way of working, but let me describe the scenario.
**User 1 is admin** and created a connection via his own generated API key
![image](https://github.com/atlanhq/atlan-java/assets/553512/6f907813-696f-4678-b7e0-e7b0bb3e7453)
He has his own api key:
![image](https://github.com/atlanhq/atlan-java/assets/553512/18eba481-39d6-488f-8df7-2d9b8232125b)

**User 2 (me) is also admin** and I generated my own api key:
![image](https://github.com/atlanhq/atlan-java/assets/553512/01e45fab-d105-4727-9ba5-5860847baf2c)
I have my own api key:
![image](https://github.com/atlanhq/atlan-java/assets/553512/97b474aa-2c9c-4ddd-b6c7-13c284f1136c)

Now when I try to query connection details using my api key(admin) which was created by my college(also admin) i get permission error:
` AssetResponse assetResponse = client.assets.get("37c70b87-0760-4049-b1aa-ed9cdf38ab86", Boolean.TRUE, Boolean.TRUE);`
The error:
```
com.atlan.exception.PermissionException: ATLAN-JAVA-403-000 Server responded with ATLAS-403-00-001: service-account-apikey-9bff22c3-a69a-46dc-8c46-e8bf3c88cfbe is not authorized to perform read entity: guid=37c70b87-0760-4049-b1aa-ed9cdf38ab86
	at com.atlan.net.LiveAtlanResponseGetter.handleApiError(LiveAtlanResponseGetter.java:210)
	at com.atlan.net.LiveAtlanResponseGetter.request(LiveAtlanResponseGetter.java:129)
	at com.atlan.net.LiveAtlanResponseGetter.request(LiveAtlanResponseGetter.java:78)
	at com.atlan.net.ApiResource.request(ApiResource.java:344)
	at com.atlan.api.AssetEndpoint.get(AssetEndpoint.java:503)
	at com.atlan.api.AssetEndpoint.get(AssetEndpoint.java:482)
	at net.pmi.atlan.api.benchmark.AtlanApiBenchmark.main(AtlanApiBenchmark.java:38)
```
Is this standard behavior?

**Comment by archenroot** [comment]
I use following code:
```
try {
            //        Atlan.setBaseUrl(System.getenv("ATLAN_BASE_URL"));
            //        Atlan.setApiToken(System.getenv("ATLAN_API_KEY"));
            Atlan.setBaseUrl(ATLAN_BASE_URL);
            Atlan.setApiToken(ATLAN_API_KEY);
            
            AtlanClient client = Atlan.getDefaultClient();
//            AssetResponse assetResponse = client.assets.get("38a4771a-f9f9-4686-8f71-15ac29aa7e4a", Boolean.TRUE, Boolean.TRUE);
            AssetResponse assetResponse = client.assets.get("37c70b87-0760-4049-b1aa-ed9cdf38ab86", Boolean.TRUE, Boolean.TRUE);
            Gson gson = new GsonBuilder().setPrettyPrinting().create();
            JsonElement jsonElement = JsonParser.parseString(assetResponse.toJson(client));
            String prettyJsonString = gson.toJson(jsonElement);
            logger.log(Level.INFO, prettyJsonString);
            System.out.println("Hello World!");
        } catch (AtlanException ex) {
            logger.log(Level.SEVERE, null, ex);
        }
```
Here is a connection property:
![image](https://github.com/atlanhq/atlan-java/assets/553512/8c7a967c-477d-4941-827c-0a3c1c8b18bc)
And I added myself to connection admins configuration:
![image](https://github.com/atlanhq/atlan-java/assets/553512/bb7576b7-f774-4f06-a72a-4c8580d44876)
Still permission error...any idea?

**Comment by archenroot** [comment]
I seems to understand the proble, when I use api key of my college it prints out:
```
INFO: {
  "entity": {
    "createTime": 1703169796884,
    "guid": "37c70b87-0760-4049-b1aa-ed9cdf38ab86",
    "createdBy": "service-account-apikey-1fc96361-22eb-4bfa-b154-8da8043acec9",
    "isIncomplete": false,
    "status": "ACTIVE",
    "typeName": "Connection",
    "updateTime": 1703334353116,
    "updatedBy": "lzitka",
    "attributes": {
      "popularityScore": 1.17549435E-38,
      "hasPopularityInsights": false,
      "sourceUpdatedAt": 0,
      "isSampleDataPreviewEnabled": false,
      "sourceLastReadAt": 0,
      "assetDbtJobLastRunStartedAt": 0,
      "adminGroups": [
        "atlan_metadata_catalog_admin_qa"
      ],
      "assetDbtJobLastRunCreatedAt": 0,
      "assetDbtJobNextRun": 0,
      "credentialStrategy": "default",
      "announcementUpdatedAt": 0,
      "vectorEmbeddingsEnabled": false,
      "qualifiedName": "test_bulk/metadata/conn1",
      "allowQueryPreview": false,
      "port": 0,
      "name": "conn1",
      "certificateUpdatedAt": 0,
      "sourceReadQueryCost": 0.0,
      "queryTimeout": 10,
      "isAIGenerated": false,
      "useObjectStorage": false,
      "assetDbtJobLastRunUpdatedAt": 0,
      "isPartial": false,
      "connectorName": "mysql",
      "adminRoles": [
        "88eb6d39-f89e-4c36-babe-5d71e7f81b9c"
      ],
      "assetMcLastSyncRunAt": 0,
      "sourceReadUserCount": 0,
      "assetDbtJobLastRun": 0,
      "policyStrategy": "default",
      "objectStorageUploadThreshold": 100000,
      "assetSodaLastSyncRunAt": 0,
      "starredCount": 0,
      "lastRowChangedAt": 0,
      "assetSodaLastScanAt": 0,
      "assetDbtJobLastRunArtifactsSaved": false,
      "assetDbtJobLastRunDequedAt": 0,
      "sourceCreatedAt": 0,
      "assetDbtJobLastRunNotificationsSent": false,
      "assetSodaCheckCount": 0,
      "vectorEmbeddingsUpdatedAt": 0,
      "__hasLineage": false,
      "assetDbtJobLastRunHasSourcesGenerated": false,
      "assetDbtJobLastRunHasDocsGenerated": false,
      "viewScore": 1.17549435E-38,
      "sourceTotalCost": 0.0,
      "lastSyncRunAt": 0,
      "popularityInsightsTimeframe": 0,
      "rowLimit": 0,
      "adminUsers": [
        "davidsamek",
        "lzitka",
        "service-account-apikey-1fc96361-22eb-4bfa-b154-8da8043acec9"
      ],
      "isEditable": true,
      "sourceReadCount": 0,
      "allowQuery": false,
      "previewCredentialStrategy": "default",
      "isDiscoverable": true,
      "category": "warehouse"
    }
  }
}
```
although I added my user as adminUser for the connection: lzitka above, my api key is not as adminUsers and that is the problem.

**Comment by archenroot** [comment]
Ok, I just need to find a way how to store my api key as admin. Closing issue.

**Comment by cmgrote** [comment]
> Ok, I just need to find a way how to store my api key as admin. Closing issue.

For now we have a custom package that we can enable on your tenant to allow you to assign API tokens as connection admins: https://solutions.atlan.com/api-token-connection-admin/

**Comment by archenroot** [comment]
I will discuss this within the team and come back later next year.
