### ISSUE TITLE
Testing 100 parallel threads for table creation and got com.atlan.exception.ApiConnectionException: ATLAN-JAVA--1-001 IOException occurred during API request to Atlan.

### ISSUE THREAD

**Issue by archenroot** [atlanhq/atlan-java#396]
I am little bit stressing the Atlan API with some parallel processing, I create a 100 threads, each of the thread make its own AtlanClient instance, the code looks like here:
```
String connectionQn = "connectionQn ";
            String databaseQn = connectionQn + "/databaseQn ";
            String schemaQn = databaseQn + "/schemaQn";
            String tableNamePrefix = "benchmarkTable";
            int tableCount = 100;
            String timeStamp = new SimpleDateFormat("yyyy.MM.dd.HH.mm.ss").format(new java.util.Date());
            Instant start = Instant.now();
            logString("START - " + timeStamp);
            ExecutorService executorService = Executors.newFixedThreadPool(10);
            List<CompletableFuture<Void>> futures = new ArrayList<>();
            for (int i = 1; i <= tableCount; ++i) {
                 final int threadId = i;
                 CompletableFuture<Void> future = CompletableFuture.runAsync(() -> {
                    try {
                        logString("Thread-" + Integer.toString(threadId) + " started - " + new SimpleDateFormat("yyyy.MM.dd.HH.mm.ss").format(new java.util.Date()));
                        AtlanClient client = Atlan.getDefaultClient();
                        String tableName = tableNamePrefix + "-" + Integer.toString(threadId);
                        String tableQn = schemaQn + "/" + tableName;
                        Table table = Table.creator(tableName, schemaQn)
                                .tableQualifiedName(tableQn)
                                .build();
                        AssetMutationResponse tableSaveResponse = client.assets.save(table);
        //                String toJson = tableSaveResponse.toJson(client);
        //                //log(toJson);
                        String assignedGuid = tableSaveResponse.getAssignedGuid(table);
                        AssetDeletionResponse deleteResponse = client.assets.delete(assignedGuid, AtlanDeleteType.DEFAULT);
        //                toJson = deleteResponse.toJson(client);
                        //log(toJson);
                        logString("Thread-" + Integer.toString(threadId) + " finished - " + new SimpleDateFormat("yyyy.MM.dd.HH.mm.ss").format(new java.util.Date()));
                    } catch (AtlanException ex) {
                         Logger.getLogger(AtlanApiBenchmark.class.getName()).log(Level.SEVERE, null, ex);
                     }
                }, executorService);
                futures.add(future);
            }
            CompletableFuture.allOf(futures.toArray(new CompletableFuture[0])).join();
            executorService.shutdown();
            
            logString("END - " + timeStamp);
            Instant end = Instant.now();
            Duration duration = Duration.between(start, end);
            logString("Duration - " + duration.toString());
```

I am creating and directly deleting, but just note deletion I can comment to measure time just for upsert. I still tune the code... so please understand I would like to see how much performance I can get from Atlan (Atlas) API.

Here is the response:
```
com.atlan.exception.ApiConnectionException: ATLAN-JAVA--1-001 IOException occurred during API request to Atlan: 
removed atlan instance info.
	at com.atlan.net.HttpURLConnectionClient.requestStream(HttpURLConnectionClient.java:52)
	at com.atlan.net.HttpURLConnectionClient.request(HttpURLConnectionClient.java:65)
	at com.atlan.net.HttpClient.sendWithTelemetry(HttpClient.java:69)
	at com.atlan.net.HttpClient.requestWithTelemetry(HttpClient.java:84)
	at com.atlan.net.HttpClient.lambda$requestWithRetries$0(HttpClient.java:141)
	at com.atlan.net.HttpClient.sendWithRetries(HttpClient.java:106)
	at com.atlan.net.HttpClient.requestWithRetries(HttpClient.java:141)
	at com.atlan.net.LiveAtlanResponseGetter.request(LiveAtlanResponseGetter.java:123)
	at com.atlan.net.LiveAtlanResponseGetter.request(LiveAtlanResponseGetter.java:78)
	at com.atlan.net.ApiResource.request(ApiResource.java:344)
	at com.atlan.net.ApiResource.request(ApiResource.java:314)
	at com.atlan.api.AssetEndpoint.save(AssetEndpoint.java:229)
	at com.atlan.api.AssetEndpoint.save(AssetEndpoint.java:194)
	at com.atlan.api.AssetEndpoint.save(AssetEndpoint.java:166)
	at com.atlan.api.AssetEndpoint.save(AssetEndpoint.java:153)
	at net.pmi.atlan.api.benchmark.AtlanApiBenchmark.lambda$main$0(AtlanApiBenchmark.java:90)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1714)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1514)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:586)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1446)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1417)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:219)
	at com.atlan.net.HttpURLConnectionClient.createAtlanConnection(HttpURLConnectionClient.java:122)
	at com.atlan.net.HttpURLConnectionClient.requestStream(HttpURLConnectionClient.java:38)
	... 19 more
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:494)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:483)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)
	... 29 more
```

NOTE: We were in touch with Simone (Atlan architect) and he suggested to use:
- cca 5 parallel threads
- cca max 20 assets per call
So here I am testing how much the endpoint can survive....thx for feedback.

Still I understand that 100 threads could be too much, but in case of overhelmed API endopint I would expect RateLimitException | Errors when the Atlan server is being overwhelmed by requests. but that is not the case, so I report it.

**Comment by archenroot** [comment]
Ok, I investigated the issue and it could I have to state that we are using Zscaler TLS inspection proxy/firewall, so I imported all 3 certificates from cert chain using following handy utility which scans the host and import the certificate in jsecacerts key store.
```
/*
 * Copyright 2006 Sun Microsystems, Inc.  All Rights Reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *   - Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *
 *   - Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in the
 *     documentation and/or other materials provided with the distribution.
 *
 *   - Neither the name of Sun Microsystems nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
 * IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/**
 * Originally from:
 * http://blogs.sun.com/andreas/resource/InstallCert.java
 * Use:
 * java InstallCert hostname
 * Example:
 *% java InstallCert ecc.fedora.redhat.com
 */

import java.net.Proxy;
import java.net.Socket;
import java.net.InetSocketAddress;
import javax.net.ssl.*;
import java.io.*;
import java.security.KeyStore;
import java.security.MessageDigest;
import java.security.cert.CertificateException;
import java.security.cert.X509Certificate;

/**
 * Class used to add the server's certificate to the KeyStore
 * with your trusted certificates.
 */
public class InstallCert {

    public static void main(String[] args) throws Exception {

        String host       = null;
        int    port       = -1;
        char[] passphrase = null;

        // proxy
        boolean           useProxy   = false;
        String            proxyHost  = null;
        int               proxyPort  = -1;
        InetSocketAddress proxyAddr  = null;
        Socket            underlying = null;

        int numArg = 0;
        int nbArgs = args.length;
        boolean invalidArgs = false;
        boolean isQuiet = false;
        while (numArg < nbArgs) {
            String arg = args[numArg++];
            if (arg.startsWith("--proxy=")) {
                String proxy = arg.substring("--proxy=".length());
                useProxy = true;
                String[] c = proxy.split(":");
                proxyHost = c[0];
                proxyPort = Integer.parseInt(c[1]);  // proxy port is mandatory (we don't default to 8080)
            }
            else if (arg.startsWith("--quiet")) {
                isQuiet = true;
            }
            else if (host == null) {  // 1st argument is the "host:port"
                String[] c = arg.split(":");
                host = c[0];
                port = (c.length == 1) ? 443 : Integer.parseInt(c[1]);
            }
            else if (passphrase == null) {  //  2nd argument is the keystore passphrase
                passphrase = arg.toCharArray();
            }
            else {
                invalidArgs = true;  // too many args
            }
        }

        if (host == null) {
            invalidArgs = true;
        }

        if (invalidArgs) {
            System.out.println("Usage: java InstallCert [--proxy=proxyHost:proxyPort] host[:port] [passphrase] [--quiet]");
            return;
        }

        // default values
        if (port       == -1  ) { port       = 443; }
        if (passphrase == null) { passphrase = "changeit".toCharArray(); }

        File file = new File("jssecacerts");
        if (file.isFile() == false) {
            char SEP = File.separatorChar;
            File dir = new File(System.getProperty("java.home") + SEP + "lib" + SEP + "security");
            file = new File(dir, "jssecacerts");
            if (file.isFile() == false) {
                file = new File(dir, "cacerts");
            }
        }
        System.out.println("Loading KeyStore " + file + "...");
        InputStream in = new FileInputStream(file);
        KeyStore ks = KeyStore.getInstance(KeyStore.getDefaultType());
        ks.load(in, passphrase);
        in.close();

        if (useProxy) {
            proxyAddr = new InetSocketAddress(proxyHost, proxyPort);
            underlying = new Socket(new Proxy(Proxy.Type.HTTP, proxyAddr));
        }

        SSLContext context = SSLContext.getInstance("TLS");
        TrustManagerFactory tmf = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
        tmf.init(ks);
        X509TrustManager defaultTrustManager = (X509TrustManager) tmf.getTrustManagers()[0];
        SavingTrustManager tm = new SavingTrustManager(defaultTrustManager);
        context.init(null, new TrustManager[]{tm}, null);
        SSLSocketFactory factory = context.getSocketFactory();

        System.out.println("Opening connection to " + host + ":" + port + (useProxy ? (" via proxy "+proxyHost+":"+proxyPort) : "") + " ...");
        SSLSocket socket;
        if (useProxy) {
            underlying.connect(new InetSocketAddress(host, port));
            socket = (SSLSocket) factory.createSocket(underlying, host, port, true);
        } else {
            socket = (SSLSocket) factory.createSocket(host, port);
        }
        socket.setSoTimeout(10000);
        try {
            System.out.println("Starting SSL handshake...");
            socket.startHandshake();
            socket.close();
            System.out.println();
            System.out.println("No errors, certificate is already trusted");
        } catch (SSLException e) {
            System.out.println();
            e.printStackTrace(System.out);
        }

        X509Certificate[] chain = tm.chain;
        if (chain == null) {
            System.out.println("Could not obtain server certificate chain");
            return;
        }

        BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));

        System.out.println();
        System.out.println("Server sent " + chain.length + " certificate(s):");
        System.out.println();
        MessageDigest sha1 = MessageDigest.getInstance("SHA1");
        MessageDigest md5 = MessageDigest.getInstance("MD5");
        for (int i = 0; i < chain.length; i++) {
            X509Certificate cert = chain[i];
            System.out.println(" " + (i + 1) + " Subject " + cert.getSubjectDN());
            System.out.println("   Issuer  " + cert.getIssuerDN());
            sha1.update(cert.getEncoded());
            System.out.println("   sha1    " + toHexString(sha1.digest()));
            md5.update(cert.getEncoded());
            System.out.println("   md5     " + toHexString(md5.digest()));
            System.out.println();
        }

        int k;
        if (isQuiet) {
            System.out.println("Adding first certificate to trusted keystore");
            k = 0;
        }
        else {
            System.out.println("Enter certificate to add to trusted keystore or 'q' to quit: [1]");
            String line = reader.readLine().trim();
            try {
                k = (line.length() == 0) ? 0 : Integer.parseInt(line) - 1;
            } catch (NumberFormatException e) {
                System.out.println("KeyStore not changed");
                return;
            }
        }

        X509Certificate cert = chain[k];
        String alias = host + "-" + (k + 1);
        ks.setCertificateEntry(alias, cert);

        OutputStream out = new FileOutputStream("jssecacerts");
        ks.store(out, passphrase);
        out.close();

        System.out.println();
        System.out.println(cert);
        System.out.println();
        System.out.println("Added certificate to keystore 'jssecacerts' using alias '" + alias + "'");
    }

    private static final char[] HEXDIGITS = "0123456789abcdef".toCharArray();

    private static String toHexString(byte[] bytes) {
        StringBuilder sb = new StringBuilder(bytes.length * 3);
        for (int b : bytes) {
            b &= 0xff;
            sb.append(HEXDIGITS[b >> 4]);
            sb.append(HEXDIGITS[b & 15]);
            sb.append(' ');
        }
        return sb.toString();
    }

    private static class SavingTrustManager implements X509TrustManager {

        private final X509TrustManager tm;
        private X509Certificate[] chain;

        SavingTrustManager(X509TrustManager tm) {
            this.tm = tm;
        }

        public X509Certificate[] getAcceptedIssuers() {
            // This change has been done due to the following resolution advised for Java 1.7+
            // http://infposs.blogspot.kr/2013/06/installcert-and-java-7.html
            return new X509Certificate[0];
            //throw new UnsupportedOperationException();
        }

        public void checkClientTrusted(X509Certificate[] chain, String authType) throws CertificateException {
            throw new UnsupportedOperationException();
        }

        public void checkServerTrusted(X509Certificate[] chain, String authType) throws CertificateException {
            this.chain = chain;
            tm.checkServerTrusted(chain, authType);
        }
    }

}
```

So far and with thread pool configured to 25 I am seeing very good performance. So closing this issue for now.

**Comment by archenroot** [comment]
Well, I again hit the issue while running 50 threads each 20 tables... I will try to lower down number of assets list and threads...

**Comment by archenroot** [comment]
I am closing this issue as I think its happening due to our SSL interception proxy. When tested communication without SSL proxy, it all works.
