### ISSUE TITLE
Enhancement suggestion - Highlight maximum GUIDs list to be deleted in bulk

### ISSUE THREAD

**Issue by archenroot** [atlanhq/atlan-java#397]
Hi,

as part of my stressing Atlan API from Java SDK I tried to delete 500 of assets in bulk delete using this code:
```
public static void CleanUp() {
        try {
            Atlan.setBaseUrl(ATLAN_BASE_URL);
            Atlan.setApiToken(ATLAN_API_KEY);
            final AtlanClient client = Atlan.getDefaultClient();
            String connectionQn = "commentionQN";
            String databaseQn = connectionQn + "databaseQn";
            String schemaQn = databaseQn + "/schemaQN";
            String tableNamePrefix = "benchmarkTableSecond";
//        client.assets.search();
            int objectCount = 0;
            var wrapper = new Object(){ int ordinal = 0; };
            int[] localCounter = new int[1];
            int[] globalCounter = new int[1];
            List<String> assetGuids = new ArrayList();
            Table.select() //
                    .where(Asset.QUALIFIED_NAME.startsWith(schemaQn)) //
                    .pageSize(50) //
                    .includeOnResults(Asset.DESCRIPTION) //
//                    .stream() //
                    .stream().parallel()
                    .filter(a -> a instanceof Table) //
                    .forEach(c -> {  try {
                        //
                        localCounter[0]++;
                        globalCounter[0]++;
                        logString("Record count - " + localCounter[0] + ", Table - " +  c.getQualifiedName());
                        assetGuids.add(c.getGuid());
                        if (localCounter[0] == 100){
                            logString("20 assets, going to delete them");
                            AssetDeletionResponse deleteResponse = client.assets.delete(assetGuids, AtlanDeleteType.HARD);
                            log(deleteResponse.toJson(client));
                            localCounter[0] = 0;
                            assetGuids.clear();
                            logString("Record count - " + localCounter[0] + ", guids size - "+  assetGuids.size());
                        }
                        logString("Global count - " + globalCounter[0]);
                } catch (AtlanException ex) {
                    Logger.getLogger(AtlanApiBenchmark.class.getName()).log(Level.SEVERE, null, ex);
                }
           }
);
        } catch (AtlanException ex) {
            Logger.getLogger(AtlanApiBenchmark.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
```

, but it failed on:
```
SEVERE: null
com.atlan.exception.ApiException: ATLAN-JAVA-400-019 Invalid response object from API: <html>
<head><title>414 Request-URI Too Large</title></head>
<body>
<center><h1>414 Request-URI Too Large</h1></center>
</body>
</html>
. (HTTP response code was 414). Additional details: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 2].
	at com.atlan.net.LiveAtlanResponseGetter.raiseMalformedJsonError(LiveAtlanResponseGetter.java:165)
	at com.atlan.net.LiveAtlanResponseGetter.handleApiError(LiveAtlanResponseGetter.java:189)
	at com.atlan.net.LiveAtlanResponseGetter.request(LiveAtlanResponseGetter.java:129)
	at com.atlan.net.LiveAtlanResponseGetter.request(LiveAtlanResponseGetter.java:78)
	at com.atlan.net.ApiResource.request(ApiResource.java:344)
	at com.atlan.api.AssetEndpoint.delete(AssetEndpoint.java:405)
	at com.atlan.api.AssetEndpoint.delete(AssetEndpoint.java:367)
	at net.pmi.atlan.api.benchmark.AtlanApiBenchmark.lambda$CleanUp$3(AtlanApiBenchmark.java:216)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at net.pmi.atlan.api.benchmark.AtlanApiBenchmark.CleanUp(AtlanApiBenchmark.java:208)
	at net.pmi.atlan.api.benchmark.AtlanApiBenchmark.main(AtlanApiBenchmark.java:84)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2481)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:752)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:676)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:2088)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:812)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4986)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4892)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3846)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3814)
	at com.atlan.net.LiveAtlanResponseGetter.handleApiError(LiveAtlanResponseGetter.java:187)
	... 18 more
```

it will be handy if documented some medium or high threshold values to be used.

**Comment by cmgrote** [comment]
We've updated the docs to include a recommended size (20-50), and include the rationale (that otherwise the URI will be too long): https://developer.atlan.com/snippets/advanced-examples/delete/#bulk-delete-assets

**Comment by archenroot** [comment]
@cmgrote - cool, thank you very much for fast response.
